version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_event_ticket
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: football1234
      POSTGRES_DB: event_ticket
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
