"""ticket_model_sector table added

Revision ID: 04fd4dfb5a71
Revises: bc7e96a0de13
Create Date: 2025-07-25 11:02:12.515033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fd4dfb5a71'
down_revision: Union[str, Sequence[str], None] = 'bc7e96a0de13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_model_sector',
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('ticket_model_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('ticket_load', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('cnpj', 'ticket_model_id', 'sector_id')
    )
    op.drop_column('ticket_model', 'price')
    op.drop_column('ticket_model', 'sector_id')
    op.drop_column('ticket_model', 'ticket_load')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_model', sa.Column('ticket_load', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ticket_model', sa.Column('sector_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ticket_model', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('ticket_model_sector')
    # ### end Alembic commands ###
