"""change primary key in login table and add a new index using email and password

Revision ID: 818fff63ec99
Revises: 0a42bb079049
Create Date: 2025-08-12 13:28:04.420550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818fff63ec99'
down_revision: Union[str, Sequence[str], None] = '0a42bb079049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_login_email_password', 'login', ['email', 'password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_login_email_password', table_name='login')
    # ### end Alembic commands ###
