"""create event_service table

Revision ID: ab495e3f874e
Revises: 0b07a7a44b44
Create Date: 2025-07-26 14:27:00.568204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab495e3f874e'
down_revision: Union[str, Sequence[str], None] = '0b07a7a44b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_service',
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('event_service_id', sa.Integer(), nullable=False),
    sa.Column('ticket_model_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_address', sa.String(), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cnpj', 'event_service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_service')
    # ### end Alembic commands ###
